<?php

namespace app\admin\model;

use think\Model;

class User extends Model
{
    //
    protected  function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function article()
    {
        return $this->hasMany("Article","uid");
    }
}
